# Generated by Django 4.2.16 on 2024-09-13 05:28

from django.db import migrations, models
import django.db.models.deletion
import school.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.CharField(default=school.models.generate_school_code, max_length=8, unique=True)),
                ('school_name', models.CharField(max_length=222)),
                ('state', models.CharField(max_length=20)),
                ('lga', models.CharField(max_length=25)),
                ('town', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=225)),
                ('year_establishment', models.IntegerField()),
                ('location', models.CharField(max_length=10)),
                ('type_of_school', models.CharField(max_length=15, null=True)),
                ('school_level', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15, unique=True)),
                ('student_name', models.CharField(max_length=225)),
                ('date_of_birth', models.DateField()),
                ('state_of_origin', models.CharField(max_length=25)),
                ('lga_of_origin', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=225)),
                ('student_class', models.CharField(max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
    ]
