# Generated by Django 4.2.16 on 2024-09-08 08:22

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.CharField(default=school.models.generate_school_code, max_length=8, unique=True)),
                ('school_name', models.CharField(max_length=222)),
                ('state', models.CharField(max_length=20)),
                ('lga', models.CharField(max_length=25)),
                ('town', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=225)),
                ('year_establishment', models.IntegerField()),
                ('location', models.CharField(max_length=10)),
            ],
        ),
    ]
