# Generated by Django 4.2.16 on 2024-09-13 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
